FROM node:26.5.0-alpine3.24

RUN apk add --no-cache tzdata

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . . 

RUN npx prisma generate

EXPOSE 8000

CMD npx prisma migrate deploy && npx prisma db seed && npm run dev