-- Add fields to tugas table for OB assignment
ALTER TABLE "tugas" ADD COLUMN IF NOT EXISTS "lantai_id" UUID REFERENCES "lantai"(id);
ALTER TABLE "tugas" ADD COLUMN IF NOT EXISTS "ob_id" UUID REFERENCES "user"(id);
ALTER TABLE "tugas" ADD COLUMN IF NOT EXISTS "status" VARCHAR(30) NOT NULL DEFAULT 'BELUM_DIKERJAKAN';
ALTER TABLE "tugas" ADD COLUMN IF NOT EXISTS "catatan" TEXT;
ALTER TABLE "tugas" ADD COLUMN IF NOT EXISTS "dikerjakan_at" TIMESTAMP(6);
ALTER TABLE "tugas" ADD COLUMN IF NOT EXISTS "selesai_at" TIMESTAMP(6);
